//go:build linux

package ebpf

import (
	"fmt"
	"net"
	"sort"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"

	t "github.com/mojtaba/portsleuth/backend/internal/collector"
)

// load attaches the XDP program (RX direction) to the configured interface.
//
// loadObjects() is generated by `bpf2go` — it returns the parsed BPF
// objects with typed handles to programs and maps. If the generated file
// (portcounter_bpf*.go) is missing, this file will fail to compile,
// signalling the user to run `go generate ./...`.
func (c *Collector) load() error {
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock: %w", err)
	}

	ifaceName := c.iface
	if ifaceName == "" || ifaceName == "auto" {
		picked, err := pickDefaultInterface()
		if err != nil {
			return err
		}
		ifaceName = picked
		c.iface = picked
	}

	objs, closeObjs, err := loadObjects()
	if err != nil {
		return fmt.Errorf("load objects: %w", err)
	}
	if closeObjs != nil {
		c.closeFns = append(c.closeFns, closeObjs)
	}

	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		return fmt.Errorf("interface %q: %w", ifaceName, err)
	}

	xdpLink, err := link.AttachXDP(link.XDPOptions{
		Program:   objs.XdpCountIngress,
		Interface: iface.Index,
		Flags:     link.XDPGenericMode,
	})
	if err != nil {
		return fmt.Errorf("attach XDP: %w", err)
	}
	c.closeFns = append(c.closeFns, xdpLink.Close)

	c.portMap = objs.PortCounters
	c.supported = true
	return nil
}

// readMap iterates the kernel map, aggregates RX+TX per (port, proto),
// and returns the top-N sorted by total bytes.
func (c *Collector) readMap(limit int) ([]t.PortBytes, error) {
	if c.portMap == nil {
		return nil, ErrNotSupported
	}
	type aggKey struct {
		port  uint16
		proto uint8
	}
	agg := map[aggKey]*t.PortBytes{}

	var key portKeyKernel
	var val portValKernel
	iter := c.portMap.Iterate()
	for iter.Next(&key, &val) {
		k := aggKey{port: key.Port, proto: key.Proto}
		entry, ok := agg[k]
		if !ok {
			entry = &t.PortBytes{
				Port:     key.Port,
				Protocol: protoName(key.Proto),
			}
			agg[k] = entry
		}
		if key.Dir == 0 { // RX
			entry.RxBytes += val.Bytes
			entry.RxPackets += val.Packets
		} else { // TX
			entry.TxBytes += val.Bytes
			entry.TxPackets += val.Packets
		}
	}
	if err := iter.Err(); err != nil {
		return nil, fmt.Errorf("map iterate: %w", err)
	}

	out := make([]t.PortBytes, 0, len(agg))
	for _, v := range agg {
		out = append(out, *v)
	}
	sort.Slice(out, func(i, j int) bool {
		return (out[i].RxBytes + out[i].TxBytes) > (out[j].RxBytes + out[j].TxBytes)
	})
	if limit > 0 && len(out) > limit {
		out = out[:limit]
	}
	return out, nil
}

func pickDefaultInterface() (string, error) {
	ifaces, err := net.Interfaces()
	if err != nil {
		return "", fmt.Errorf("list interfaces: %w", err)
	}
	for _, iface := range ifaces {
		if iface.Flags&net.FlagLoopback == 0 && iface.Flags&net.FlagUp != 0 {
			return iface.Name, nil
		}
	}
	return "", fmt.Errorf("no suitable interface")
}

func protoName(p uint8) string {
	switch p {
	case 6:
		return "tcp"
	case 17:
		return "udp"
	}
	return "unknown"
}

// Mirrors `struct port_key` in port_counter.c (4 bytes total).
type portKeyKernel struct {
	Port  uint16
	Proto uint8
	Dir   uint8
}

// Mirrors `struct port_val`.
type portValKernel struct {
	Bytes   uint64
	Packets uint64
}
